# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shop.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OtakuShop_main_window(object):
    def setupUi(self, OtakuShop_main_window):
        OtakuShop_main_window.setObjectName("OtakuShop_main_window")
        OtakuShop_main_window.resize(600, 700)
        OtakuShop_main_window.setStyleSheet("background-color: rgb(1, 176, 241);")
        OtakuShop_main_window.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.centralwidget = QtWidgets.QWidget(OtakuShop_main_window)
        self.centralwidget.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.centralwidget.setObjectName("centralwidget")
        self.input_login = QtWidgets.QTextEdit(self.centralwidget)
        self.input_login.setGeometry(QtCore.QRect(90, 220, 400, 50))
        self.input_login.setStyleSheet("background-color: rgb(0, 160, 218);")
        self.input_login.setObjectName("input_login")
        self.input_password = QtWidgets.QTextEdit(self.centralwidget)
        self.input_password.setGeometry(QtCore.QRect(90, 310, 400, 50))
        self.input_password.setStyleSheet("background-color: rgb(0, 160, 218);")
        self.input_password.setObjectName("input_password")
        self.acc_inn_btn = QtWidgets.QPushButton(self.centralwidget)
        self.acc_inn_btn.setGeometry(QtCore.QRect(90, 390, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Anime Ace v05")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.acc_inn_btn.setFont(font)
        self.acc_inn_btn.setStyleSheet("background-color: rgb(70,130,180);")
        self.acc_inn_btn.setObjectName("acc_inn_btn")
        self.acc_reg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.acc_reg_btn.setGeometry(QtCore.QRect(90, 470, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Anime Ace v05")
        font.setPointSize(15)
        self.acc_reg_btn.setFont(font)
        self.acc_reg_btn.setStyleSheet("background-color: rgb(70,130,180);")
        self.acc_reg_btn.setObjectName("acc_reg_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 30, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Anime Ace v05")
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 80, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Anime Ace v05")
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 180, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Anime Ace v05")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 270, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Anime Ace v05")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        OtakuShop_main_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(OtakuShop_main_window)
        QtCore.QMetaObject.connectSlotsByName(OtakuShop_main_window)

    def retranslateUi(self, OtakuShop_main_window):
        _translate = QtCore.QCoreApplication.translate
        OtakuShop_main_window.setWindowTitle(_translate("OtakuShop_main_window", "OtakuShop"))
        self.acc_inn_btn.setText(_translate("OtakuShop_main_window", "ВОЙТИ"))
        self.acc_reg_btn.setText(_translate("OtakuShop_main_window", "зарегистрироваться"))
        self.label.setText(_translate("OtakuShop_main_window", "Магазин "))
        self.label_2.setText(_translate("OtakuShop_main_window", "OtakuShop"))
        self.label_3.setText(_translate("OtakuShop_main_window", "Логин:"))
        self.label_4.setText(_translate("OtakuShop_main_window", "Пароль:"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OtakuShop_main_window = QtWidgets.QMainWindow()
    ui = Ui_OtakuShop_main_window()
    ui.setupUi(OtakuShop_main_window)
    OtakuShop_main_window.show()
    sys.exit(app.exec_())
